#step 1 : 	creating a temp working dir to put all intermediate .go , .c , .o files 

mkdir -p work

#step 2 :	generating files required for the cgo translations

CGO_LDFLAGS='"-g" "-O2"' go tool cgo -objdir ./work -importpath gsoc -- -I ./work -g -O2 ./gsoc.go
#here cgo generates the intermediate files and dumps into temporary work directory ..i takes the .go generated by swig

#step 3 : 	generating object files for the c files generated by cgo tool 

cd work
gcc -I ../ -fPIC -m64 -pthread -fmessage-length=0 -I ./ -g -O2 -o first_go.o -c _cgo_export.c
gcc -I ../ -fPIC -m64 -pthread -fmessage-length=0 -I ./ -g -O2 -o second_go.o -c gsoc.cgo2.c
gcc -I ../ -fPIC -m64 -pthread -fmessage-length=0 -I ./ -g -O2 -o _cgo_main.o -c _cgo_main.c
cd ..

#step 4 :	compile the source and generate .o files 
# this is the step where we need all the source files to get compiled to .o as we put all the .o files together in step 5

g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I ./work/ -g -O2 -o ./work/input1.o -c /home/oem/Desktop/gsoc/database.cc
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I ./work/ -g -O2 -o ./work/input2.o -c document.cc
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I ./work/ -g -O2 -o ./work/input3.o -c stem.cc
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I ./work/ -g -O2 -o ./work/input4.o -c gsoc_wrap.cxx

#step 5 : compile and merge them to make and archive 

cd work

g++ -fPIC -m64 -pthread -fmessage-length=0 -o _cgo_.o _cgo_main.o first_go.o second_go.o input1.o input2.o input3.o input4.o
go tool cgo -dynpackage gsoc -dynimport _cgo_.o -dynout _cgo_import.go
go tool compile -o gsoc.a -p gsoc -importcfg importcfg -pack -c=4 _cgo_gotypes.go gsoc.cgo1.go _cgo_import.go
go tool pack r gsoc.a first_go.o second_go.o input1.o input2.o input3.o input4.o

#step 6 :  move the generated package to go pkg directory so that you can import it

mv gsoc.a /usr/local/go/pkg/linux_amd64


#   --------AFTER GENERATING THE STATIC LIB we generate the shared lib-----------------------
#go tool link -o ./work/libgsoc.so -importcfg ./work/importcfg.link -installsuffix dynlink -buildmode=shared -extld=g++ gsoc=/usr/local/go/pkg/linux_amd64_dynlink/gsoc.a runtime/cgo=/usr/local/go/pkg/linux_amd64_dynlink/runtime/cgo.a
# mv work/libgsoc.so /usr/local/go/pkg/linux_amd64_dynlink/libgsoc.so
