// Code generated by cmd/cgo; DO NOT EDIT.

//line ./gsoc.go:1:1
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: gsoc.i

package gsoc

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
extern void _wrap_Swig_free_gsoc_028db1e2336ef482(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_gsoc_028db1e2336ef482(swig_intgo arg1);
extern uintptr_t _wrap_new_StringVector__SWIG_0_gsoc_028db1e2336ef482(void);
extern uintptr_t _wrap_new_StringVector__SWIG_1_gsoc_028db1e2336ef482(swig_type_1 arg1);
extern swig_type_2 _wrap_StringVector_size_gsoc_028db1e2336ef482(uintptr_t arg1);
extern swig_type_3 _wrap_StringVector_capacity_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_StringVector_reserve_gsoc_028db1e2336ef482(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_StringVector_isEmpty_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_StringVector_clear_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_StringVector_add_gsoc_028db1e2336ef482(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_StringVector_get_gsoc_028db1e2336ef482(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_StringVector_set_gsoc_028db1e2336ef482(uintptr_t arg1, swig_intgo arg2, swig_type_7 arg3);
extern void _wrap_delete_StringVector_gsoc_028db1e2336ef482(uintptr_t arg1);
extern uintptr_t _wrap_new_ByteVector__SWIG_0_gsoc_028db1e2336ef482(void);
extern uintptr_t _wrap_new_ByteVector__SWIG_1_gsoc_028db1e2336ef482(swig_type_8 arg1);
extern swig_type_9 _wrap_ByteVector_size_gsoc_028db1e2336ef482(uintptr_t arg1);
extern swig_type_10 _wrap_ByteVector_capacity_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_ByteVector_reserve_gsoc_028db1e2336ef482(uintptr_t arg1, swig_type_11 arg2);
extern _Bool _wrap_ByteVector_isEmpty_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_ByteVector_clear_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_ByteVector_add_gsoc_028db1e2336ef482(uintptr_t arg1, char arg2);
extern char _wrap_ByteVector_get_gsoc_028db1e2336ef482(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_ByteVector_set_gsoc_028db1e2336ef482(uintptr_t arg1, swig_intgo arg2, char arg3);
extern void _wrap_delete_ByteVector_gsoc_028db1e2336ef482(uintptr_t arg1);
extern swig_intgo _wrap_GSOC_OPEN_get_gsoc_028db1e2336ef482(void);
extern swig_intgo _wrap_GSOC_CLOSE_get_gsoc_028db1e2336ef482(void);
extern uintptr_t _wrap_new_Stem_gsoc_028db1e2336ef482(void);
extern void _wrap_delete_Stem_gsoc_028db1e2336ef482(uintptr_t arg1);
extern uintptr_t _wrap_Stem_applyStem_gsoc_028db1e2336ef482(uintptr_t arg1, swig_type_12 arg2);
extern void _wrap_func_stem_gsoc_028db1e2336ef482(void);
extern uintptr_t _wrap_new_Database_gsoc_028db1e2336ef482(void);
extern void _wrap_delete_Database_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_Database_printId_gsoc_028db1e2336ef482(uintptr_t arg1);
extern swig_intgo _wrap_Database_getId_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_Database_setId_gsoc_028db1e2336ef482(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_database_func_gsoc_028db1e2336ef482(void);
extern uintptr_t _wrap_new_Document_gsoc_028db1e2336ef482(void);
extern void _wrap_delete_Document_gsoc_028db1e2336ef482(uintptr_t arg1);
extern void _wrap_Document_display_gsoc_028db1e2336ef482(uintptr_t arg1);
extern _Bool _wrap_Document_insert_gsoc_028db1e2336ef482(uintptr_t arg1, swig_type_13 arg2);
extern void _wrap_Document_NumberOfDocuments_set_gsoc_028db1e2336ef482(swig_intgo arg1);
extern swig_intgo _wrap_Document_NumberOfDocuments_get_gsoc_028db1e2336ef482(void);
#undef intgo
*/
import _ "unsafe"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	( /*line :120:2*/_Cfunc__wrap_Swig_free_gsoc_028db1e2336ef482 /*line :120:40*/)( /*line :120:42*/_Ctype_uintptr_t /*line :120:53*/(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(( /*line :126:21*/_Cfunc__wrap_Swig_malloc_gsoc_028db1e2336ef482 /*line :126:61*/)( /*line :126:63*/_Ctype_swig_intgo /*line :126:75*/(_swig_i_0)))
	return swig_r
}

type SwigcptrStringVector uintptr

func (p SwigcptrStringVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStringVector) SwigIsStringVector() {
}

func NewStringVector__SWIG_0() (_swig_ret StringVector) {
	var swig_r StringVector
	swig_r = (StringVector)(SwigcptrStringVector(( /*line :141:47*/_Cfunc__wrap_new_StringVector__SWIG_0_gsoc_028db1e2336ef482 /*line :141:100*/)()))
	return swig_r
}

func NewStringVector__SWIG_1(arg1 int64) (_swig_ret StringVector) {
	var swig_r StringVector
	_swig_i_0 := arg1
	swig_r = (StringVector)(SwigcptrStringVector(( /*line :148:47*/_Cfunc__wrap_new_StringVector__SWIG_1_gsoc_028db1e2336ef482 /*line :148:100*/)( /*line :148:102*/_Ctype_swig_type_1 /*line :148:115*/(_swig_i_0))))
	return swig_r
}

func NewStringVector(a ...interface{}) StringVector {
	argc := len(a)
	if argc == 0 {
		return NewStringVector__SWIG_0()
	}
	if argc == 1 {
		return NewStringVector__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrStringVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(( /*line :166:19*/_Cfunc__wrap_StringVector_size_gsoc_028db1e2336ef482 /*line :166:65*/)( /*line :166:67*/_Ctype_uintptr_t /*line :166:78*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(( /*line :173:19*/_Cfunc__wrap_StringVector_capacity_gsoc_028db1e2336ef482 /*line :173:69*/)( /*line :173:71*/_Ctype_uintptr_t /*line :173:82*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	( /*line :180:2*/_Cfunc__wrap_StringVector_reserve_gsoc_028db1e2336ef482 /*line :180:51*/)( /*line :180:53*/_Ctype_uintptr_t /*line :180:64*/(_swig_i_0),  /*line :180:77*/_Ctype_swig_type_4 /*line :180:90*/(_swig_i_1))
}

func (arg1 SwigcptrStringVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(( /*line :186:18*/_Cfunc__wrap_StringVector_isEmpty_gsoc_028db1e2336ef482 /*line :186:67*/)( /*line :186:69*/_Ctype_uintptr_t /*line :186:80*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Clear() {
	_swig_i_0 := arg1
	( /*line :192:2*/_Cfunc__wrap_StringVector_clear_gsoc_028db1e2336ef482 /*line :192:49*/)( /*line :192:51*/_Ctype_uintptr_t /*line :192:62*/(_swig_i_0))
}

func (arg1 SwigcptrStringVector) Add(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	( /*line :198:2*/_Cfunc__wrap_StringVector_add_gsoc_028db1e2336ef482 /*line :198:47*/)( /*line :198:49*/_Ctype_uintptr_t /*line :198:60*/(_swig_i_0), *(* /*line :198:76*/_Ctype_struct___0 /*line :198:89*/)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrStringVector) Get(arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := ( /*line :208:14*/_Cfunc__wrap_StringVector_get_gsoc_028db1e2336ef482 /*line :208:59*/)( /*line :208:61*/_Ctype_uintptr_t /*line :208:72*/(_swig_i_0),  /*line :208:85*/_Ctype_swig_intgo /*line :208:97*/(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrStringVector) Set(arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	( /*line :219:2*/_Cfunc__wrap_StringVector_set_gsoc_028db1e2336ef482 /*line :219:47*/)( /*line :219:49*/_Ctype_uintptr_t /*line :219:60*/(_swig_i_0),  /*line :219:73*/_Ctype_swig_intgo /*line :219:85*/(_swig_i_1), *(* /*line :219:101*/_Ctype_struct___0 /*line :219:114*/)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func DeleteStringVector(arg1 StringVector) {
	_swig_i_0 := arg1.Swigcptr()
	( /*line :227:2*/_Cfunc__wrap_delete_StringVector_gsoc_028db1e2336ef482 /*line :227:50*/)( /*line :227:52*/_Ctype_uintptr_t /*line :227:63*/(_swig_i_0))
}

type StringVector interface {
	Swigcptr() uintptr
	SwigIsStringVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 string)
	Get(arg2 int) (_swig_ret string)
	Set(arg2 int, arg3 string)
}

type SwigcptrByteVector uintptr

func (p SwigcptrByteVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrByteVector) SwigIsByteVector() {
}

func NewByteVector__SWIG_0() (_swig_ret ByteVector) {
	var swig_r ByteVector
	swig_r = (ByteVector)(SwigcptrByteVector(( /*line :254:43*/_Cfunc__wrap_new_ByteVector__SWIG_0_gsoc_028db1e2336ef482 /*line :254:94*/)()))
	return swig_r
}

func NewByteVector__SWIG_1(arg1 int64) (_swig_ret ByteVector) {
	var swig_r ByteVector
	_swig_i_0 := arg1
	swig_r = (ByteVector)(SwigcptrByteVector(( /*line :261:43*/_Cfunc__wrap_new_ByteVector__SWIG_1_gsoc_028db1e2336ef482 /*line :261:94*/)( /*line :261:96*/_Ctype_swig_type_8 /*line :261:109*/(_swig_i_0))))
	return swig_r
}

func NewByteVector(a ...interface{}) ByteVector {
	argc := len(a)
	if argc == 0 {
		return NewByteVector__SWIG_0()
	}
	if argc == 1 {
		return NewByteVector__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrByteVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(( /*line :279:19*/_Cfunc__wrap_ByteVector_size_gsoc_028db1e2336ef482 /*line :279:63*/)( /*line :279:65*/_Ctype_uintptr_t /*line :279:76*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(( /*line :286:19*/_Cfunc__wrap_ByteVector_capacity_gsoc_028db1e2336ef482 /*line :286:67*/)( /*line :286:69*/_Ctype_uintptr_t /*line :286:80*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	( /*line :293:2*/_Cfunc__wrap_ByteVector_reserve_gsoc_028db1e2336ef482 /*line :293:49*/)( /*line :293:51*/_Ctype_uintptr_t /*line :293:62*/(_swig_i_0),  /*line :293:75*/_Ctype_swig_type_11 /*line :293:89*/(_swig_i_1))
}

func (arg1 SwigcptrByteVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(( /*line :299:18*/_Cfunc__wrap_ByteVector_isEmpty_gsoc_028db1e2336ef482 /*line :299:65*/)( /*line :299:67*/_Ctype_uintptr_t /*line :299:78*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Clear() {
	_swig_i_0 := arg1
	( /*line :305:2*/_Cfunc__wrap_ByteVector_clear_gsoc_028db1e2336ef482 /*line :305:47*/)( /*line :305:49*/_Ctype_uintptr_t /*line :305:60*/(_swig_i_0))
}

func (arg1 SwigcptrByteVector) Add(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	( /*line :311:2*/_Cfunc__wrap_ByteVector_add_gsoc_028db1e2336ef482 /*line :311:45*/)( /*line :311:47*/_Ctype_uintptr_t /*line :311:58*/(_swig_i_0),  /*line :311:71*/_Ctype_char /*line :311:77*/(_swig_i_1))
}

func (arg1 SwigcptrByteVector) Get(arg2 int) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (byte)(( /*line :318:18*/_Cfunc__wrap_ByteVector_get_gsoc_028db1e2336ef482 /*line :318:61*/)( /*line :318:63*/_Ctype_uintptr_t /*line :318:74*/(_swig_i_0),  /*line :318:87*/_Ctype_swig_intgo /*line :318:99*/(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Set(arg2 int, arg3 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	( /*line :326:2*/_Cfunc__wrap_ByteVector_set_gsoc_028db1e2336ef482 /*line :326:45*/)( /*line :326:47*/_Ctype_uintptr_t /*line :326:58*/(_swig_i_0),  /*line :326:71*/_Ctype_swig_intgo /*line :326:83*/(_swig_i_1),  /*line :326:96*/_Ctype_char /*line :326:102*/(_swig_i_2))
}

func DeleteByteVector(arg1 ByteVector) {
	_swig_i_0 := arg1.Swigcptr()
	( /*line :331:2*/_Cfunc__wrap_delete_ByteVector_gsoc_028db1e2336ef482 /*line :331:48*/)( /*line :331:50*/_Ctype_uintptr_t /*line :331:61*/(_swig_i_0))
}

type ByteVector interface {
	Swigcptr() uintptr
	SwigIsByteVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 byte)
	Get(arg2 int) (_swig_ret byte)
	Set(arg2 int, arg3 byte)
}

func GetGSOC_OPEN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(( /*line :349:17*/_Cfunc__wrap_GSOC_OPEN_get_gsoc_028db1e2336ef482 /*line :349:59*/)())
	return swig_r
}

func GetGSOC_CLOSE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(( /*line :355:17*/_Cfunc__wrap_GSOC_CLOSE_get_gsoc_028db1e2336ef482 /*line :355:60*/)())
	return swig_r
}

const VERSION float64 = 1.5
const GSOC int = 2020
type SwigcptrStem uintptr

func (p SwigcptrStem) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStem) SwigIsStem() {
}

func NewStem() (_swig_ret Stem) {
	var swig_r Stem
	swig_r = (Stem)(SwigcptrStem(( /*line :372:31*/_Cfunc__wrap_new_Stem_gsoc_028db1e2336ef482 /*line :372:68*/)()))
	return swig_r
}

func DeleteStem(arg1 Stem) {
	_swig_i_0 := arg1.Swigcptr()
	( /*line :378:2*/_Cfunc__wrap_delete_Stem_gsoc_028db1e2336ef482 /*line :378:42*/)( /*line :378:44*/_Ctype_uintptr_t /*line :378:55*/(_swig_i_0))
}

func (arg1 SwigcptrStem) ApplyStem(arg2 string) (_swig_ret ByteVector) {
	var swig_r ByteVector
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ByteVector)(SwigcptrByteVector(( /*line :385:43*/_Cfunc__wrap_Stem_applyStem_gsoc_028db1e2336ef482 /*line :385:86*/)( /*line :385:88*/_Ctype_uintptr_t /*line :385:99*/(_swig_i_0), *(* /*line :385:115*/_Ctype_struct___0 /*line :385:129*/)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

type Stem interface {
	Swigcptr() uintptr
	SwigIsStem()
	ApplyStem(arg2 string) (_swig_ret ByteVector)
}

func Func_stem() {
	( /*line :399:2*/_Cfunc__wrap_func_stem_gsoc_028db1e2336ef482 /*line :399:40*/)()
}

type SwigcptrDatabase uintptr

func (p SwigcptrDatabase) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDatabase) SwigIsDatabase() {
}

func NewDatabase() (_swig_ret Database) {
	var swig_r Database
	swig_r = (Database)(SwigcptrDatabase(( /*line :413:39*/_Cfunc__wrap_new_Database_gsoc_028db1e2336ef482 /*line :413:80*/)()))
	return swig_r
}

func DeleteDatabase(arg1 Database) {
	_swig_i_0 := arg1.Swigcptr()
	( /*line :419:2*/_Cfunc__wrap_delete_Database_gsoc_028db1e2336ef482 /*line :419:46*/)( /*line :419:48*/_Ctype_uintptr_t /*line :419:59*/(_swig_i_0))
}

func (arg1 SwigcptrDatabase) PrintId() {
	_swig_i_0 := arg1
	( /*line :424:2*/_Cfunc__wrap_Database_printId_gsoc_028db1e2336ef482 /*line :424:47*/)( /*line :424:49*/_Ctype_uintptr_t /*line :424:60*/(_swig_i_0))
}

func (arg1 SwigcptrDatabase) GetId() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(( /*line :430:17*/_Cfunc__wrap_Database_getId_gsoc_028db1e2336ef482 /*line :430:60*/)( /*line :430:62*/_Ctype_uintptr_t /*line :430:73*/(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDatabase) SetId(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	( /*line :437:2*/_Cfunc__wrap_Database_setId_gsoc_028db1e2336ef482 /*line :437:45*/)( /*line :437:47*/_Ctype_uintptr_t /*line :437:58*/(_swig_i_0),  /*line :437:71*/_Ctype_swig_intgo /*line :437:83*/(_swig_i_1))
}

type Database interface {
	Swigcptr() uintptr
	SwigIsDatabase()
	PrintId()
	GetId() (_swig_ret int)
	SetId(arg2 int)
}

func Database_func() {
	( /*line :449:2*/_Cfunc__wrap_database_func_gsoc_028db1e2336ef482 /*line :449:44*/)()
}

type SwigcptrDocument uintptr

func (p SwigcptrDocument) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDocument) SwigIsDocument() {
}

func NewDocument() (_swig_ret Document) {
	var swig_r Document
	swig_r = (Document)(SwigcptrDocument(( /*line :463:39*/_Cfunc__wrap_new_Document_gsoc_028db1e2336ef482 /*line :463:80*/)()))
	return swig_r
}

func DeleteDocument(arg1 Document) {
	_swig_i_0 := arg1.Swigcptr()
	( /*line :469:2*/_Cfunc__wrap_delete_Document_gsoc_028db1e2336ef482 /*line :469:46*/)( /*line :469:48*/_Ctype_uintptr_t /*line :469:59*/(_swig_i_0))
}

func (arg1 SwigcptrDocument) Display() {
	_swig_i_0 := arg1
	( /*line :474:2*/_Cfunc__wrap_Document_display_gsoc_028db1e2336ef482 /*line :474:47*/)( /*line :474:49*/_Ctype_uintptr_t /*line :474:60*/(_swig_i_0))
}

func (arg1 SwigcptrDocument) Insert(arg2 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(( /*line :481:18*/_Cfunc__wrap_Document_insert_gsoc_028db1e2336ef482 /*line :481:62*/)( /*line :481:64*/_Ctype_uintptr_t /*line :481:75*/(_swig_i_0), *(* /*line :481:91*/_Ctype_struct___0 /*line :481:105*/)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetDocumentNumberOfDocuments(arg1 int) {
	_swig_i_0 := arg1
	( /*line :490:2*/_Cfunc__wrap_Document_NumberOfDocuments_set_gsoc_028db1e2336ef482 /*line :490:61*/)( /*line :490:63*/_Ctype_swig_intgo /*line :490:75*/(_swig_i_0))
}

func GetDocumentNumberOfDocuments() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(( /*line :495:17*/_Cfunc__wrap_Document_NumberOfDocuments_get_gsoc_028db1e2336ef482 /*line :495:76*/)())
	return swig_r
}

type Document interface {
	Swigcptr() uintptr
	SwigIsDocument()
	Display()
	Insert(arg2 string) (_swig_ret bool)
}


